# Generated by Django 2.2 on 2020-12-19 06:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='added_to_wishlist',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='post_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='post_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='release_year',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
