# Generated by Django 2.2 on 2020-12-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201219_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
