# Generated by Django 2.2 on 2020-12-20 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201219_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='added_to_wishlist',
            field=models.IntegerField(default=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='release_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
