# Generated by Django 2.2 on 2020-12-20 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201220_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='added_to_wishlist',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
